### PR TITLE
General Parser

### PR DESCRIPTION
**Pull request by mhotan**
Created a CSV Parser that parses through all the Trip csv files, compressed or not, in a directory.  Forwards  all the trip data via callback to an implementing servce

### CODE REVIEW

**Comment by coyotebush** [comment]
At a glance the parsing code looks fine. Two things, though:
- I'd prefer not to actually check the (rather large) data into Git. If we want it to be in a well-known location, we can create e.g. `/data`, add `data/*.zip` to `.gitignore`, and have everyone put the data files there.
- If it's not too much trouble, could we take the graph-related commits off this branch?

**Comment by mhotan** [comment]
Ok I have no problem with ignoring the data files.  Do we really need to take the graph related commits off this branch?  I can put it on a different branch for the following commits.

**Comment by coyotebush** [comment]
No big deal about the graph commits, but can you rebase such that the data files are gone from history entirely? `git rebase -i master` then rearrange/edit lines so that it looks something like

```
pick 297c3e3
pick 56eb981
fixup 6b8fe28
pick 5200e65
```

Or shall I?

**Comment by mhotan** [comment]
Ill probably mess it up.  If you could do it I would appreciate it.

**Comment by coyotebush** [comment]
That should do it. Sorry that that screws up your graph-init-db branch; let me figure out the right invocation that would fix that.

**Pull request merged**
