### PR TITLE
Expose query methods to JS

### PR DESCRIPTION
**Pull request by coyotebush**
This makes the interesting methods currently implemented on StationRepository, BikeRepository and StationDAO available via JS functions on the CitiBikeApi object. Example usage in `main.html`.

### CODE REVIEW

**Comment by coyotebush** [comment]
Oh, findDistanceBtwStations is gone now? I'll see about exposing findStationPairsWithDistance in its place.

**Comment by mhotan** [comment]
The Api looks great.  That method replacement sound fine.  I am going to Checkout the branch and manage the merge with master.

**Comment by coyotebush** [comment]
Merging doesn't make sense until I work on findStationPairsWithDistance. (The merge fails _because_ I modified findDistanceBtwStations but it's been deleted.)

**Comment by mhotan** [comment]
OK I was going to leave a method stub but I will wait then.  Do you think that method might be better off as two seperate methods.   One that finds all stations within a certain distance of another station(s), from a specific point, or within a certain area?

**Comment by coyotebush** [comment]
I'm not convinced that findStationPairsWithDistance is useful, and findDistanceBtwStations sounded useful (although it didn't seem to work when I tried it). But for this branch my task is just to make usable what's been implemented.

**Comment by coyotebush** [comment]
That should do it, although I haven't been able to test findStationPairsWithDistance since my Postgres database isn't up to date with the latest schema.

**Comment by coyotebush** [comment]
OK, findStationPairsWithDistance works :+1:

**Comment by coyotebush** [comment]
You can merge this as is, or else I can work on adding more server-side functionality and include that here.

**Comment by mhotan** [comment]
Awesome great job.

**Pull request closed without merging**
